### ISSUE TITLE
Side-Loading

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3-Sail#41]
If you are building a new app, it should be possible to "side-load" this into the app-directory without having to modify / create a directory of your own.

This would allow people who are building apps from scratch to test them out without having to worry about creating a directory.

This would work particularly well with the FDC3 Workbench, which would allow them to test receiving/sending contexts and intents via channels in the app.

This is something that I used extensively when developing apps in Symphony (see https://symphonyoss.github.io/Integrations-Docs/quickstart/):

> Run your application again as indicated above, to get the new bundle.js information packaged.
> Launch the Symphony client on your browser, adding your bundle.js as path of the query parameters in the URL. For instance, using the Foundation Dev Pod with the above ngrok sample URL: https://foundation-dev.symphony.com?bundle=https://d74a790c.ngrok.io/apps/zapier/bundle.json.

**Comment by nkolba** [comment]
@robmoffat  @ColinEberhardt  @sebbenmbarek  
I think the simplest and most feasible approach for this would be to add a button into the tools menu to allows the end user to load an arbitrary URL into a new tab as a side app.    Loading the app this way (even if it isn't in the directory) will provide it with most FDC3 functionality including intents (as long as the app is running), channels, and context broadcast.  

Since what directory the electron implementation is pointing to will vary, there isn't a consistent and reliable way at this time to update the actual directory.

**Comment by robmoffat** [comment]
Nick pretty much demo'd this at OSFF.  Closing
